# Generated by Django 6.1 on 2026-08-23 01:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
